// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhDRr0jX-gJZfMYz8dw2ZASLWo3kH0JtA',
    appId: '1:385618920843:web:6dbbe5ce50efda3848db8e',
    messagingSenderId: '385618920843',
    projectId: 'green-gentem-d9ced',
    authDomain: 'green-gentem-d9ced.firebaseapp.com',
    storageBucket: 'green-gentem-d9ced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAurU2MLDMHtBex-uae7oDrEWm5gHR5Qjk',
    appId: '1:385618920843:android:76ea3f901603f3a648db8e',
    messagingSenderId: '385618920843',
    projectId: 'green-gentem-d9ced',
    storageBucket: 'green-gentem-d9ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwec27-ORBsvZ7wVrxWd3NuLnE4bVLIOQ',
    appId: '1:385618920843:ios:7e48b152d67d280248db8e',
    messagingSenderId: '385618920843',
    projectId: 'green-gentem-d9ced',
    storageBucket: 'green-gentem-d9ced.appspot.com',
    iosClientId: '385618920843-30i5mn4a3dr8jngac1h68p8imknhroph.apps.googleusercontent.com',
    iosBundleId: 'com.example.gg1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwec27-ORBsvZ7wVrxWd3NuLnE4bVLIOQ',
    appId: '1:385618920843:ios:7e48b152d67d280248db8e',
    messagingSenderId: '385618920843',
    projectId: 'green-gentem-d9ced',
    storageBucket: 'green-gentem-d9ced.appspot.com',
    iosClientId: '385618920843-30i5mn4a3dr8jngac1h68p8imknhroph.apps.googleusercontent.com',
    iosBundleId: 'com.example.gg1',
  );
}
